### ISSUE TITLE
[Question] Always run into `Unable to get provider com.google.firebase.provider.FirebaseInitProvider` on Android.

### ISSUE THREAD

**Issue by ArthurKValladares** [firebase/firebase-cpp-sdk#1216]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: _____
  * Firebase C++ SDK version: 10.5.0
  * Main Firebase Components in concern: Core (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)

### [REQUIRED] Please describe the question here:
I have been unable to get past the error `java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path` in my Android project, while following the instructions on: https://firebase.google.com/docs/cpp/setup?platform=android

Full error log:

<details>
<summary>Details</summary>

 ````
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brainiumstudios.jumbline, PID: 23067
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/~~KMmeAg7ukH40oedpUpMrKA==/com.brainiumstudios.jumbline-9xH9-VIbLvD_inSrMvG1vw==/lib/arm, /data/app/~~KMmeAg7ukH40oedpUpMrKA==/com.brainiumstudios.jumbline-9xH9-VIbLvD_inSrMvG1vw==/base.apk!/lib/armeabi-v7a, /data/app/~~KMmeAg7ukH40oedpUpMrKA==/com.brainiumstudios.jumbline-9xH9-VIbLvD_inSrMvG1vw==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/~~KMmeAg7ukH40oedpUpMrKA==/com.brainiumstudios.jumbline-9xH9-VIbLvD_inSrMvG1vw==/split_config.en.apk!/lib/armeabi-v7a, /data/app/~~KMmeAg7ukH40oedpUpMrKA==/com.brainiumstudios.jumbline-9xH9-VIbLvD_inSrMvG1vw==/split_config.xxhdpi.apk!/lib/armeabi-v7a, /data/app/~~KMmeAg7ukH40oedpUpMrKA==/com.brainiumstudios.jumbline-9xH9-VIbLvD_inSrMvG1vw==/split_core_asset_pack.apk!/lib/armeabi-v7a, /system/lib, /system_ext/lib, /product/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:7430)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6942)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6713)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/~~KMmeAg7ukH40oedpUpMrKA==/com.brainiumstudios.jumbline-9xH9-VIbLvD_inSrMvG1vw==/lib/arm, /data/app/~~KMmeAg7ukH40oedpUpMrKA==/com.brainiumstudios.jumbline-9xH9-VIbLvD_inSrMvG1vw==/base.apk!/lib/armeabi-v7a, /data/app/~~KMmeAg7ukH40oedpUpMrKA==/com.brainiumstudios.jumbline-9xH9-VIbLvD_inSrMvG1vw==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/~~KMmeAg7ukH40oedpUpMrKA==/com.brainiumstudios.jumbline-9xH9-VIbLvD_inSrMvG1vw==/split_config.en.apk!/lib/armeabi-v7a, /data/app/~~KMmeAg7ukH40oedpUpMrKA==/com.brainiumstudios.jumbline-9xH9-VIbLvD_inSrMvG1vw==/split_config.xxhdpi.apk!/lib/armeabi-v7a, /data/app/~~KMmeAg7ukH40oedpUpMrKA==/com.brainiumstudios.jumbline-9xH9-VIbLvD_inSrMvG1vw==/split_core_asset_pack.apk!/lib/armeabi-v7a, /system/lib, /system_ext/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7414)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6942) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6713) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:247) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
 ````

</details>

Module-level `build.gradle`

<details>
<summary>Details</summary>

````
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.1'
        classpath 'com.google.gms:google-services:4.3.15'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register("clean").configure {
    delete("build")
}
````

</details>

App-level `build.gradle`

<details>
<summary>Details</summary>

````
plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
    id 'rustPlugin'
}

android {
    compileSdk = 33
    defaultConfig {
        applicationId 'com.brainiumstudios.jumbline'
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
        externalNativeBuild {
            cmake {
                cppFlags ''
                arguments "-DFIREBASE_CPP_SDK_DIR=../../../../vendor/firebase_cpp_sdk/"
            }
        }
    }
    sourceSets {
        main {
            // Vulkan validation layers
            jniLibs.srcDir System.getenv("NDK_HOME") + '/sources/third_party/vulkan/src/build-android/jniLibs'
        }
    }
    buildTypes {
        debug {
            debuggable true
            jniDebuggable true
            minifyEnabled true
            packagingOptions {
                jniLibs.keepDebugSymbols += "*/arm64-v8a/*.so"
                jniLibs.keepDebugSymbols += "*/armeabi-v7a/*.so"
                jniLibs.keepDebugSymbols +=  "*/x86/*.so"
                jniLibs.keepDebugSymbols += "*/x86_64/*.so"
            }
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            proguardFile file("../../../../vendor/firebase_cpp_sdk/libs/android/app.pro")
            proguardFile file("../../../../vendor/firebase_cpp_sdk/libs/android/analytics.pro")
        }
    }
    flavorDimensions.add("abi")
    productFlavors {
        arm64 {
            dimension "abi"
            ndk {
                abiFilters = ["arm64-v8a"]
            }
        }
        arm {
            dimension "abi"
            ndk {
                abiFilters = ["armeabi-v7a"]
            }
        }
        x86 {
            dimension "abi"
            ndk {
                abiFilters = ["x86"]
            }
        }
        x86_64 {
            dimension "abi"
            ndk {
                abiFilters = ["x86_64"]
            }
        }
    }

    assetPacks = [":core_asset_pack"]
    namespace 'com.brainiumstudios.jumbline'
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.18.1'
        }
    }
}

rust {
    rootDirRel = "../../../"
    targets = ["aarch64", "armv7", "i686", "x86_64"]
    arches = ["arm64", "arm", "x86", "x86_64"]
}

afterEvaluate {
    android.applicationVariants.all {
        buildType.name.capitalize()
        productFlavors.forEach { _ ->
            def archAndBuildType = name.capitalize()
            tasks["merge${archAndBuildType}JniLibFolders"].dependsOn(tasks["rustBuild${archAndBuildType}"])
        }
    }
}

apply from: "../../../../vendor/firebase_cpp_sdk/Android/firebase_dependencies.gradle"
firebaseCpp.dependencies {
    analytics
}

apply plugin: 'com.google.gms.google-services'
````

</details>

My setup is a little unconventional as I am building and running a Rust app, so I might be simply missing an extra step, but since everything links correctly and this is a runtime Java crash, it felt to me like this was more likely a gradle-side problem.

**Comment by DellaBitta** [comment]
Hi @ArthurKValladares,

Are you building in release mode? If so, are you using [Proguard](https://firebase.google.com/docs/cpp/setup?platform=android)? There's an older,  similar [issue reported here.](https://stackoverflow.com/questions/59936834/multidex-proguard-and-firebase).

I have to admit that there's a lot going on here in the gradle file that I'm not familiar with regarding the rust and productFlavor directives.

I'd suggest checking out one of the build.gardle files at the app level for our integration tests. Here's the [Auth build.gradle file](https://github.com/firebase/firebase-cpp-sdk/blob/main/auth/integration_test/build.gradle) for instance. Attempt to get that to work with a simple C++ app, and then start migrating the rust code into your build.

Additionally it would be helpful to get some more information about your setup. Could you post a build log so that we may see if there are any errors in it? A lack of that class probably means either a) it's a proguard problem, or b) the tools aren't linking in one of the Firebase libraries for the target architectures. Though as you mentioned, things compile. So that's a conundrum.

**Comment by ArthurKValladares** [comment]
This is happening in a debug build. Here are the relevant build logs:

<details>
<summary>Details</summary>

````
> Configure project :app
[CXX5106] NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. If you delete ndk.dir from local.properties and set android.ndkVersion to [23.0.7599858] then NDK at /Users/arthurvalladares/Library/Android/sdk/ndk/23.0.7599858 will be used. https://developer.android.com/r/studio-ui/ndk-dir

> Task :app:processArmDebugGoogleServices
Execution optimizations have been disabled for task ':app:processArmDebugGoogleServices' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/arthurvalladares/Documents/Brainium/jumbline-reboot/projects/android/jumbline/app/build/generated/res/google-services/arm/debug'. Reason: Task ':app:rustBuildArmDebug' uses this output of task ':app:processArmDebugGoogleServices' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#implicit_dependency for more details about this problem.
````

</details>

I'll look into porting my code into the sample project over the next couple days.

**Comment by ArthurKValladares** [comment]
I'm closing this as I've run into a similar problem with a different library, so I think the problem is completely on my side. Thanks for the help!
