### ISSUE TITLE
Firebase is not building on Ubuntu 20.10

### ISSUE THREAD

**Issue by canatella** [firebase/firebase-cpp-sdk#269]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: source
  * Firebase C++ SDK version: 7.0.1
  * Problematic Firebase Component: Build system (Auth, Database, etc.)
  * Other Firebase Components in use: n/a  (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: Linux (Mac, Windows, or Linux)
  * Platform you are targeting: desktop (iOS, Android, and/or desktop)

### [REQUIRED] Please describe the issue here:

Building fails on Ubuntu 20.10. I need to apply multiple patch to get it working, I use the following cmake settings:
```
                'BUILD_TESTING': 'OFF',
                'CMAKE_DEBUG_POSTFIX': '',
                'DISABLE_CXX11': 'OFF',
                'FIREBASE_CPP_BUILD_TESTS': 'OFF',
                'FIREBASE_FORCE_FAKE_SECURE_STORAGE': 'ON',
                'FIREBASE_INCLUDE_LIBRARY_DEFAULT': 'OFF',
                'FIREBASE_INCLUDE_ANALYTICS': 'ON',
                'FIREBASE_INCLUDE_AUTH': 'ON',
                'FIREBASE_INCLUDE_FIRESTORE': 'ON',
                'FIREBASE_INCLUDE_DATABASE': 'OFF',
                'FIREBASE_CPP_BUILD_PACKAGE': 'ON'
```

#### Trying to build inexistent files
```
-- Configuring done
CMake Error at firestore/CMakeLists.txt:172 (add_library):
  Cannot find source file:

    src/ios/firebase_firestore_settings_ios.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at firestore/CMakeLists.txt:172 (add_library):
  No SOURCES given to target: firebase_firestore


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Needed to remove `src/ios/firebase_firestore_settings_ios.cc` from the `CMakeLists.txt`

Also I need to add 
```
    src/ios/create_firebase_metadata_provider_desktop.cc
    src/ios/firebase_metadata_provider_desktop.cc
```

#### Bugged version of firestore ios

```
cd /home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore-build/Firestore/Protos && python /home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore/Firestore/Protos/build_protos.py --nanopb --protoc=/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore-build/external/src/grpc-build/third_party/protobuf/protoc-3.11.2.0 --pythonpath=/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore-build/external/src/protobuf/python:/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore-build/external/src/nanopb/generator --output_dir=/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore/Firestore/Protos -I/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore/Firestore/Protos/protos -I/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore-build/external/src/nanopb/generator -I/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore-build/external/src/protobuf/src
google/firestore/v1/common.proto:20:1: warning: Import google/api/annotations.proto is unused.
google/firestore/v1/document.proto:20:1: warning: Import google/api/annotations.proto is unused.
google/firestore/v1/query.proto:20:1: warning: Import google/api/annotations.proto is unused.
google/firestore/v1/write.proto:20:1: warning: Import google/api/annotations.proto is unused.

         ********************************************************************
         *** Failed to import the protocol definitions for generator.     ***
         *** You have to run 'make' in the nanopb/generator/proto folder. ***
         ********************************************************************
    
Traceback (most recent call last):
  File "/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore/Firestore/Protos/nanopb_cpp_generator.py", line 25, in <module>
    import nanopb_generator as nanopb
  File "/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore-build/external/src/nanopb/generator/nanopb_generator.py", line 37, in <module>
    from .proto import nanopb_pb2, plugin_pb2
ImportError: attempted relative import with no known parent package
--nanopb_out: protoc-gen-nanopb: Plugin failed with status code 1.
Traceback (most recent call last):
  File "/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore/Firestore/Protos/build_protos.py", line 392, in <module>
    main()
  File "/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore/Firestore/Protos/build_protos.py", line 96, in main
    NanopbGenerator(args, all_proto_files).run()
  File "/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore/Firestore/Protos/build_protos.py", line 119, in run
    self.__run_generator(nanopb_out)
  File "/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore/Firestore/Protos/build_protos.py", line 149, in __run_generator
    run_protoc(self.args, cmd)
  File "/home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/build/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/external/src/firestore/Firestore/Protos/build_protos.py", line 251, in run_protoc
    subprocess.check_call(cmd, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
```

That is fixed if I use firestore ios `2311c36dbcd19f2f6e89f0f2747582f0647442f7` instead of `05026f3df92cdee7b91fccc72a7195be2618acdf`

#### The build apparently includes test files:

```
ld.lld: error: duplicate symbol: main
>>> defined at main_for_testing_build.cc:1 (firestore/src/common/main_for_testing_build.cc:1)
>>>            main_for_testing_build.cc.o:(main) in archive /home/dam/.conan/data/firebase-sdk/7.0.1+bloom5/bloomlife/testing/package/077ae3b1b2ee3d195574ff15861e77a3dac68f4b/lib/libfirebase_firestore.a
```

I need to remove that from the `CMakeLists.txt` to be able to link against the generated libraries.

**Comment by canatella** [comment]
I seems it is also missing `src/common/compiler_info.cc`

**Comment by canatella** [comment]
And trying to reproduce on the quickstart test app, I know get a 
```
 undefined reference to `absl::lts_2020_02_25::variant_internal::ThrowBadVariantAccess()'
/usr/bin/ld: firebase-cpp-sdk/firestore/libfirebase_firestore.a(field_value_ios.cc.o): in function `std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, firebase::firestore::FieldValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, firebase::firestore::FieldValue> > > const& absl::lts_2020_02_25::variant_internal::TypedThrowBadVariantAccess<std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, firebase::firestore::FieldValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, firebase::firestore::FieldValue> > > const&>()':
field_value_ios.cc:(.text._ZN4absl14lts_2020_02_2516variant_internal26TypedThrowBadVariantAccessIRKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN8firebase9firestore10FieldValueESt4hashIS9_ESt8equal_toIS9_ESaISt4pairIKS9_SC_EEEEET_v[_ZN4absl14lts_2020_02_2516variant_internal26TypedThrowBadVariantAccessIRKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN8firebase9firestore10FieldValueESt4hashIS9_ESt8equal_toIS9_ESaISt4pairIKS9_SC_EEEEET_v]+0x5): undefined reference to `absl::lts_2020_02_25::variant_internal::ThrowBadVariantAccess()'
```

**Comment by var-const** [comment]
Thank you for (another) very detailed issue report! I will look into this. Just to clarify, do the fixes you listed make the build work, or are there any failures even after that?

**Comment by canatella** [comment]
No after that the quick start app is working. I also updated the nanopb version to 0.3.9.7, mostly for [this fix](https://github.com/nanopb/nanopb/blob/049485ff557178f646d573eca3bd647f543b760b/CHANGELOG.txt#L147) which hit me at some point but it seems to be building/running without now... But there are  lots of nanopb small fixes in there so might be good to still update. Another problem I still have though is that the `cmake install` target does not install all the dependencies libs, so to reuse the firebase I just built I need to copy them by hand, but this is more for convenience. I can open a new issue for that if you want.

**Comment by vimanyu** [comment]
Hi @canatella,
Which branch are you using for the build?

Can you try on the `release/7.0.1` branch? In that branch, I do not see any mention of `src/ios/firebase_firestore_settings_ios.cc` in firestore/CMakeLists.txt and I also see the 2 files you had to manually added already added there. 

We haven't noticed this specific error while building the SDK on Github actions on linux (ubuntu 18). Once I have the branch, I can try building it on Ubuntu 20.

**Comment by canatella** [comment]
I was building master. I would expect that master is buildable at any time, if not, it would be nice to add a note in the README, because this is what most people would expect from a master branch on github. The `release/7.0.1` branch is building correctly though :+1:

**Comment by vimanyu** [comment]
Sorry about that and yes, I agree. We were in the middle of a long term project and decided to accumulate our changes in another branch (dev). We will soon be updating master and it should be good to go.
