### ISSUE TITLE
[Question] Segfaults when creating default app

### ISSUE THREAD

**Issue by TimWhiting** [firebase/firebase-cpp-sdk#612]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: repo
  * Firebase C++ SDK version: latest from repo
  * Main Firebase Components in concern: app
  * Other Firebase Components in use: app
  * Platform you are using the C++ SDK on: Linux
  * Platform you are targeting: desktop

### [REQUIRED] Please describe the question here:

Update: I was able to resolve the build errors by using gcc-8. Maybe that should be mentioned as the lowest version of gcc required.

But then with a very simple app, with the built libraries copied to the lib folder, and a google-services.json with the requested fields valid, the following app segfaults.
```
Static tracepoint 1 at 0x7ffff70124e1: file ../sysdeps/x86_64/multiarch/strlen-avx2.S, line 65.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x0000555555562c7e in firebase::AppOptions::LoadFromJsonConfig(char const*, firebase::AppOptions*) ()
#2  0x0000555555559ee7 in firebase::(anonymous namespace)::LoadAppOptionsFromJsonConfigFile(char const*, firebase::AppOptions*) ()
#3  0x0000555555559bef in firebase::AppOptions::LoadDefault(firebase::AppOptions*) ()
#4  0x000055555555a04a in firebase::App::Create() ()
#5  0x000055555555989f in main ()
```

Example code
```cpp

#include <firebase/app.h>
#include <iostream>
#include <unistd.h>

int main(int argc, char** argv) {

  firebase::App* app = firebase::App::Create();
  // std::cerr << "Database URL " << app->options().database_url() << std::endl;
  std::cerr << "Storage Bucket " << app->options().storage_bucket() << std::endl;
  std::cout << "Project ID " << app->options().project_id() << std::endl;
  std::cout << "API Key " << app->options().api_key() << std::endl;
  std::cout << "App ID " << app->options().app_id() << std::endl;
  // std::cout << "Messaging ID " << app->options().messaging_sender_id() << std::endl;
  // std::cout << "GA Tracking ID " << app->options().ga_tracking_id() << std::endl;
  std::cout << std::endl;
  std::cout.flush();

}
```

Makefile
```make
all:
	g++ test.cc -Iinclude -Llib -lfirebase_app -lflatbuffers -lpthread
```
When I only print out the API key and App ID it doesn't segfault but I get bogus information: (It reports the API Key as being the actual storage bucket url and it reports the App ID as an empty string, though it is obviously not).

**Comment by TimWhiting** [comment]
Forgot the -D_GLIBCXX_USE_CXX11_ABI=0 in my makefile
